// Code generated by protoc-gen-go. DO NOT EDIT.
// source: builder/output.proto

package builder

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Binary struct {
	Location             string   `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Binary) Reset()         { *m = Binary{} }
func (m *Binary) String() string { return proto.CompactTextString(m) }
func (*Binary) ProtoMessage()    {}
func (*Binary) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4329064f5894bb6, []int{0}
}

func (m *Binary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Binary.Unmarshal(m, b)
}
func (m *Binary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Binary.Marshal(b, m, deterministic)
}
func (m *Binary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Binary.Merge(m, src)
}
func (m *Binary) XXX_Size() int {
	return xxx_messageInfo_Binary.Size(m)
}
func (m *Binary) XXX_DiscardUnknown() {
	xxx_messageInfo_Binary.DiscardUnknown(m)
}

var xxx_messageInfo_Binary proto.InternalMessageInfo

func (m *Binary) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type Files struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Files) Reset()         { *m = Files{} }
func (m *Files) String() string { return proto.CompactTextString(m) }
func (*Files) ProtoMessage()    {}
func (*Files) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4329064f5894bb6, []int{1}
}

func (m *Files) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Files.Unmarshal(m, b)
}
func (m *Files) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Files.Marshal(b, m, deterministic)
}
func (m *Files) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Files.Merge(m, src)
}
func (m *Files) XXX_Size() int {
	return xxx_messageInfo_Files.Size(m)
}
func (m *Files) XXX_DiscardUnknown() {
	xxx_messageInfo_Files.DiscardUnknown(m)
}

var xxx_messageInfo_Files proto.InternalMessageInfo

func (m *Files) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*Binary)(nil), "platform.Binary")
	proto.RegisterType((*Files)(nil), "platform.Files")
}

func init() {
	proto.RegisterFile("builder/output.proto", fileDescriptor_b4329064f5894bb6)
}

var fileDescriptor_b4329064f5894bb6 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0xce, 0xbd, 0xaa, 0xc2, 0x40,
	0x10, 0xc5, 0x71, 0x02, 0xf7, 0x86, 0xb8, 0xe5, 0x62, 0x21, 0xda, 0x48, 0xb0, 0xb0, 0x49, 0xb6,
	0x10, 0xc4, 0x3a, 0x85, 0x0f, 0x60, 0x69, 0xb7, 0xf9, 0xda, 0x0c, 0x6e, 0x76, 0x86, 0x75, 0x06,
	0x49, 0x9e, 0x5e, 0x08, 0xc1, 0xee, 0x1c, 0xf8, 0x17, 0x3f, 0xb5, 0xad, 0x05, 0x7c, 0xdb, 0x45,
	0x83, 0xc2, 0x24, 0x5c, 0x52, 0x44, 0x46, 0x9d, 0x91, 0xb7, 0xdc, 0x63, 0x1c, 0xf3, 0x93, 0x4a,
	0x2b, 0x08, 0x36, 0x4e, 0x7a, 0xaf, 0x32, 0x8f, 0x8d, 0x65, 0xc0, 0xb0, 0x4b, 0x8e, 0xc9, 0x79,
	0xf3, 0xf8, 0xfd, 0xfc, 0xa0, 0xfe, 0xef, 0xe0, 0xbb, 0xb7, 0xd6, 0xea, 0x8f, 0x2c, 0x0f, 0x6b,
	0xb0, 0xec, 0xea, 0xf6, 0xbc, 0x3a, 0xe0, 0x41, 0xea, 0xb2, 0xc1, 0xd1, 0xb4, 0x10, 0x1c, 0x76,
	0x96, 0x21, 0xb8, 0x5e, 0xe6, 0xd9, 0x7c, 0xec, 0x44, 0x08, 0x81, 0x0b, 0xf2, 0xe2, 0x20, 0x14,
	0xf4, 0x72, 0x66, 0x35, 0xd5, 0xe9, 0xa2, 0xb9, 0x7c, 0x03, 0x00, 0x00, 0xff, 0xff, 0x54, 0x7a,
	0xf0, 0x92, 0xa5, 0x00, 0x00, 0x00,
}
